# Jekyll configuration

name: engrXiv Blog
description: The blog for the Engineering Archive.

# url is currently only used only for the RSS feed in feed.xml
url: http://blog.engrxiv.org

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-81495458-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'engrxiv'
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge

exclude: ['README.md', 'LICENSE']
